# Generated by Django 4.2.5 on 2024-06-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_image_post_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_paid_content",
            field=models.BooleanField(default=False),
        ),
    ]
